version: '4.0'
services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app/client
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    networks:
      - my-network
    environment:
      CASSANDRA_AUTH_DISABLED: "true"

  elasticsearch:
    image: elasticsearch:8.5.3
    ports:
      - "9200:9200"
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'false'
      ES_JAVA_OPTS: '-Xmx2g -Xms2g'
    networks:
      - my-network
    tmpfs:
      - /usr/share/elasticsearch/data
    #volumes:
    #  - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.3
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - my-network
    ports:
      - "5601:5601"

  app:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - cassandra
      - elasticsearch
    environment:
      - CASSANDRA_CONTACT_POINTS=cassandra
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
    networks:
      - my-network

volumes:
  elasticsearch_data:
    driver: local

networks:
  my-network:
    driver: bridge